import { Router } from 'express';
import db from '../db/database.js';
import * as c from '../controllers/inventory.js';
import * as constants from '../utils/constants.js';
import { fail } from '../utils/validation.js';
import { answer } from '../controllers/assistant.js';
const router=Router();
router.get('/health',(req,res)=>res.json({status:'ok'}));
router.get('/assistant/status',(req,res)=>res.json({configured:!!process.env.GROQ_API_KEY&&process.env.AI_ENABLED!=='false',provider:'Groq + LangChain'}));
let aiRequests=0,aiWindow=Date.now();
router.post('/assistant',async(req,res)=>{if(Date.now()-aiWindow>60000){aiRequests=0;aiWindow=Date.now();}if(++aiRequests>20)fail('Assistant request limit reached. Please try again in a minute.',429);res.json(await answer(req.body));});
router.get('/metadata',(req,res)=>res.json({...constants,locations:db.prepare('SELECT * FROM locations ORDER BY name').all()}));
router.get('/assets',(req,res)=>res.json(c.listAssets(req.query)));
router.get('/assets/:id',(req,res)=>res.json(c.detail(req.params.id)));
router.post('/assets',(req,res)=>res.status(201).json(c.createAsset(req.body)));
router.put('/assets/:id',(req,res)=>res.json(c.updateAsset(req.params.id,req.body)));
router.patch('/assets/:id/lifecycle',(req,res)=>{if(!constants.stages.includes(req.body?.stage)) fail('Invalid lifecycle stage');res.json(c.updateAsset(req.params.id,{lifecycle_stage:req.body.stage}));});
router.delete('/assets/:id',(req,res)=>{c.deleteAsset(req.params.id);res.status(204).end();});
router.get('/maintenance',(req,res)=>res.json(c.maintenance()));
router.get('/assets/:id/maintenance',(req,res)=>{c.asset(req.params.id);res.json(c.maintenance(req.params.id));});
router.post('/assets/:id/maintenance',(req,res)=>res.status(201).json(c.createMaintenance(req.params.id,req.body)));
router.put('/maintenance/:id',(req,res)=>res.json(c.updateMaintenance(req.params.id,req.body)));
router.patch('/maintenance/:id/complete',(req,res)=>res.json(c.updateMaintenance(req.params.id,{...req.body,status:'COMPLETED'})));
router.delete('/maintenance/:id',(req,res)=>{c.deleteMaintenance(req.params.id);res.status(204).end();});
router.get('/dashboard',(req,res)=>res.json(c.dashboard()));
router.get('/locations',(req,res)=>res.json(db.prepare('SELECT l.*,COUNT(a.id) AS asset_count,COALESCE(SUM(a.purchase_cost),0) AS total_value FROM locations l LEFT JOIN assets a ON a.location=l.name GROUP BY l.id ORDER BY l.name').all()));
export default router;
