import Database from 'better-sqlite3';
import { mkdirSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const here = dirname(fileURLToPath(import.meta.url));
const filename = process.env.DB_PATH || resolve(here, '../data/assets.db');
if (filename !== ':memory:') mkdirSync(dirname(filename), { recursive: true });
const db = new Database(filename);
db.pragma('foreign_keys = ON');
db.pragma('journal_mode = WAL');
db.exec(readFileSync(resolve(here, 'schema.sql'), 'utf8'));
export default db;
