import db from './database.js';
import { createAsset, createMaintenance, updateMaintenance, updateAsset } from '../controllers/inventory.js';
import { addDays, addYears, format } from 'date-fns';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';
const day=n=>format(addDays(new Date(),n),'yyyy-MM-dd');
export function seed() {
 if(db.prepare('SELECT COUNT(*) AS n FROM assets').get().n) return false;
 db.transaction(()=>{
 const locations=['Main Plant','Utility Block','Server Room','Admin Building','Warehouse','Production Floor A','Production Floor B','Electrical Room','Pump House','Security Control Room'];
 for(const name of locations) db.prepare('INSERT OR IGNORE INTO locations (name,type,address,city,state) VALUES (?,?,?,?,?)').run(name,'Industrial campus','MIDC Industrial Estate, Phase II','Pune','Maharashtra');
 const rows=[['500 KVA Transformer','Electrical','ABB',1250000,7],['Diesel Generator DG-01','Generator','Cummins',1850000,1],['Chiller Unit CH-02','HVAC','Blue Star',2400000,1],['Water Pump WP-04','Pump','Kirloskar',185000,8],['Cisco Core Switch','Network Equipment','Cisco',420000,2],['Dell PowerEdge Server','Server','Dell',680000,2],['Fire Pump FP-01','Fire Safety','Kirloskar',320000,8],['Passenger Elevator EL-02','Elevator','KONE',2200000,3],['CCTV NVR Unit','CCTV','Hikvision',65000,9],['Rooftop Solar Inverter','Solar Equipment','Sungrow',450000,0],['Air Compressor AC-03','Compressor','Atlas Copco',760000,5],['RO Treatment Plant','Water System','Ion Exchange',850000,1],['Distribution Transformer T-02','Transformer','Siemens',1450000,7],['Electric Forklift FL-01','Vehicle','Godrej',1200000,4],['Access Control Panel','Building Equipment','Honeywell',95000,3],['Workshop Tool Station','Other','Bosch',75000,6],['Precision AC PAC-01','HVAC','Vertiv',520000,2],['Backup Generator DG-02','Generator','Ashok Leyland',950000,0],['Booster Pump BP-02','Pump','Grundfos',145000,8],['Fire Alarm Panel','Fire Safety','Honeywell',210000,9],['Edge Server SR-03','Server','HPE',380000,2],['Solar Array Controller','Solar Equipment','Schneider',175000,0],['Warehouse Ventilation Unit','HVAC','Voltas',280000,4],['Production Motor M-09','Electrical','ABB',135000,6]];
 const stages=['OPERATIONAL','OPERATIONAL','MAINTENANCE','OPERATIONAL','OPERATIONAL','OPERATIONAL','MAINTENANCE','OPERATIONAL','END_OF_LIFE','OPERATIONAL','MAINTENANCE','OPERATIONAL','OPERATIONAL','OPERATIONAL','INSTALLED','RECEIVED','OPERATIONAL','PROCURED','END_OF_LIFE','OPERATIONAL','PLANNED','PLANNED','RETIRED','OPERATIONAL'];
 rows.forEach(([name,category,manufacturer,cost,loc],i)=>{
 const purchase=format(addYears(addDays(new Date(),i===8?-20:i===18?110:-i*9),i===8||i===18?-8:-2),'yyyy-MM-dd');
 const a=createAsset({name,category,manufacturer,purchase_cost:cost,location:locations[loc],model:`${manufacturer.split(' ')[0].toUpperCase()}-${100+i}`,serial_number:`IN-PN-2024-${String(i+1).padStart(5,'0')}`,description:`${name} supporting campus operations. Managed by the facilities and infrastructure team.`,purchase_date:purchase,expected_life_years:8,warranty_expiry:day(i===1?25:i===4?55:200+i*15),supplier:'Tata Projects / Industrial Supply India',department:loc===2?'IT Operations':'Facilities & Operations',custodian:['Arjun Mehta','Priya Sharma','Rahul Desai','Neha Patel'][i%4],lifecycle_stage:stages[i],condition:['GOOD','GOOD','POOR','EXCELLENT','GOOD','FAIR','CRITICAL','GOOD','POOR','EXCELLENT'][i%10],criticality:['HIGH','CRITICAL','HIGH','MEDIUM'][i%4],installation_date:stages[i]==='PLANNED'||stages[i]==='PROCURED'?null:purchase,commissioning_date:stages[i]==='OPERATIONAL'?purchase:null});
 if(i<8) { const m=createMaintenance(a.id,{title:['Annual load test','Oil & filter replacement','Chiller refrigerant inspection','Seal and bearing inspection','Firmware and failover review','Server hardware inspection','Fire pump pressure test','Lift safety inspection'][i],maintenance_type:i===2?'CORRECTIVE':'PREVENTIVE',scheduled_date:day([-7,-3,3,8,16,25,-20,-15][i]),technician:['Suresh Patil','Anita Rao','Vikram Singh'][i%3],vendor:'Integrated Facility Services',cost:2500+i*1750});if(i>=6) updateMaintenance(m.id,{status:'COMPLETED',completed_date:day(-5),findings:'Inspection completed; readings within tolerance.',action_taken:'Serviced and tested.'}); }
 });
 })(); return true;
}
if(process.argv[1]&&resolve(process.argv[1])===fileURLToPath(import.meta.url)){console.log(seed()?'Seeded 24 assets and 8 maintenance jobs.':'Existing data preserved; seed skipped.');db.close();}
