import { useState } from 'react';
import { ShieldCheck } from 'lucide-react';
import { useAuth } from '../services/auth';
import { PageHeading, useApp } from '../components/UI';
import { PasswordField } from './Login';
export default function Account(){const {user,changePassword}=useAuth(),{notify}=useApp();const [values,setValues]=useState({currentPassword:'',newPassword:'',confirm:''}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function submit(e){e.preventDefault();setError('');if(values.newPassword!==values.confirm){setError('New passwords do not match.');return;}setBusy(true);try{await changePassword({currentPassword:values.currentPassword,newPassword:values.newPassword});setValues({currentPassword:'',newPassword:'',confirm:''});notify('Password changed. Other sessions have been signed out.');}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <><PageHeading title="Your account" description="Manage your identity and keep your workspace access secure."/><section className="card account-card"><div className="card-heading"><h2>Profile</h2><ShieldCheck size={19}/></div><dl><div><dt>Name</dt><dd>{user.name}</dd></div><div><dt>Email</dt><dd>{user.email}</dd></div><div><dt>Access</dt><dd>Workspace administrator</dd></div></dl></section><section className="card account-card"><div className="card-heading"><div><h2>Change password</h2><p>Changing your password signs out all other sessions.</p></div></div><form className="account-form" onSubmit={submit}><PasswordField label="Current password" value={values.currentPassword} onChange={e=>setValues({...values,currentPassword:e.target.value})}/><PasswordField label="New password" value={values.newPassword} onChange={e=>setValues({...values,newPassword:e.target.value})} autoComplete="new-password" minLength={12}/><small className="password-hint">Use 12 or more characters, up to 72 UTF-8 bytes.</small><PasswordField label="Confirm new password" value={values.confirm} onChange={e=>setValues({...values,confirm:e.target.value})} autoComplete="new-password" minLength={12}/>{error&&<div className="error" role="alert">{error}</div>}<button className="button primary" disabled={busy}>{busy?'Updating…':'Update password'}</button></form></section></>;
}
