import { useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Save, ArrowLeft } from 'lucide-react';
import { api, useApi } from '../services/api';
import { PageHeading, LoadState, useApp } from '../components/UI';
import { label } from '../utils/format';
export default function AssetForm(){const {id}=useParams();const state=useApi(id?`/assets/${id}`:'/metadata');if(state.loading||state.error)return <LoadState {...state} retry={state.refresh}/>;return <Form key={id||'new'} asset={id?state.data:null}/>;}
function Form({asset}) {const {metadata,notify}=useApp(),navigate=useNavigate();const [values,setValues]=useState(asset||{name:'',category:'Electrical',lifecycle_stage:'PLANNED',condition:'GOOD',criticality:'MEDIUM',purchase_cost:0});const [error,setError]=useState(''),[busy,setBusy]=useState(false);
 const sections=[['Basic information','Identify the equipment and its technical specifications',[['name','Asset name','text',true],['category','Category',metadata.categories,true],['manufacturer','Manufacturer'],['model','Model'],['serial_number','Serial number'],['description','Description','textarea']]],['Procurement & financials','Record purchase, warranty, and useful life',[['purchase_date','Purchase date','date'],['purchase_cost','Purchase cost (₹)','number'],['supplier','Supplier'],['warranty_expiry','Warranty expiry','date'],['expected_life_years','Expected useful life (years)','number']]],['Ownership & placement','Make accountability and location clear',[['location','Location',metadata.locations.map(x=>x.name)],['department','Department'],['custodian','Custodian']]],['Operational details','Track the current stage and asset health',[['lifecycle_stage','Lifecycle stage',metadata.stages],['condition','Condition',metadata.conditions],['criticality','Criticality',metadata.criticalities],['installation_date','Installation date','date'],['commissioning_date','Commissioning date','date'],['notes','Notes','textarea']]]];
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{const allowed=sections.flatMap(s=>s[2].map(f=>f[0]));const body=Object.fromEntries(allowed.filter(k=>values[k]!==undefined).map(k=>[k,values[k]]));const a=await api(asset?`/assets/${asset.id}`:'/assets',asset?'PUT':'POST',body);notify(asset?'Asset updated':'Asset registered');navigate(`/assets/${a.id}`);}catch(e){setError(e.message);}finally{setBusy(false);}}
 return <><Link className="back-link" to={asset?`/assets/${asset.id}`:'/assets'}><ArrowLeft size={15}/>Back to {asset?'asset':'inventory'}</Link><PageHeading title={asset?'Edit asset':'Register a new asset'} description="Build a complete digital record for the entire asset lifecycle."/><form onSubmit={submit}>{sections.map(([title,description,fields],i)=><section className="card form-section" key={title}><div className="form-section-title"><span className="section-number">0{i+1}</span><h2>{title}</h2><p>{description}</p></div><div className="form-grid">{fields.map(([key,title,type='text',required])=><label key={key} className={type==='textarea'?'full-width':''}>{title}{required&&' *'}{Array.isArray(type)?<select aria-label={title} value={values[key]||''} required={required} onChange={e=>setValues({...values,[key]:e.target.value})}><option value="">Select {title.toLowerCase()}</option>{type.map(v=><option key={v} value={v}>{label(v)}</option>)}</select>:type==='textarea'?<textarea rows={3} value={values[key]||''} onChange={e=>setValues({...values,[key]:e.target.value})}/>:<input type={type} required={required} min={key==='expected_life_years'?1:type==='number'?0:undefined} max={key==='expected_life_years'?100:undefined} step={key==='purchase_cost'?'0.01':type==='number'?'1':undefined} value={values[key]??''} onChange={e=>setValues({...values,[key]:e.target.value})}/>}</label>)}</div></section>)}{error&&<div className="error" role="alert">{error}</div>}<div className="form-actions"><Link className="button" to={asset?`/assets/${asset.id}`:'/assets'}>Cancel</Link><button disabled={busy} className="button primary"><Save size={16}/>{busy?'Saving…':'Save asset'}</button></div></form></>;
}
