import { Link, useSearchParams } from 'react-router-dom';
import { Search, SlidersHorizontal, Download, ArrowUpRight } from 'lucide-react';
import { useApi } from '../services/api';
import { PageHeading, LoadState, DataTable, StatusBadge, EmptyState, useApp } from '../components/UI';
import { label, exportCsv } from '../utils/format';
export default function Assets(){const [params,setParams]=useSearchParams();const {metadata}=useApp();const {data:assets,loading,error,refresh}=useApi('/assets?'+params.toString());
 function set(key,value){const next=new URLSearchParams(params);value?next.set(key,value):next.delete(key);setParams(next,{replace:true});}
 return <><PageHeading title="Asset inventory" description="One source of truth for every asset, at every stage."><button className="button" disabled={!assets?.length} onClick={()=>exportCsv(assets)}><Download size={16}/>Export CSV</button></PageHeading><section className="card inventory-card"><div className="inventory-toolbar"><div className="input-search"><Search size={18}/><input aria-label="Search assets" placeholder="Search code, name, serial number, custodian…" value={params.get('search')||''} onChange={e=>set('search',e.target.value)}/></div><span className="subtle">{assets?.length??'…'} assets</span></div><div className="filters"><SlidersHorizontal size={17}/>{[['category','Category',metadata.categories],['stage','Lifecycle',metadata.stages],['condition','Condition',metadata.conditions],['criticality','Criticality',metadata.criticalities],['location','Location',metadata.locations.map(l=>l.name)]].map(([key,title,options])=><select aria-label={title} key={key} value={params.get(key)||''} onChange={e=>set(key,e.target.value)}><option value="">All {title.toLowerCase()}</option>{options.map(v=><option key={v} value={v}>{label(v)}</option>)}</select>)}<button className="text-button" onClick={()=>setParams({})}>Clear filters</button></div>{loading||error?<LoadState loading={loading} error={error} retry={refresh}/>:assets.length?<DataTable headers={['Asset code','Asset','Category','Location','Lifecycle','Condition','Criticality','Custodian','Actions']}>{assets.map(a=><tr key={a.id}><td><Link className="code" to={`/assets/${a.id}`}>{a.asset_code}</Link></td><td><Link className="asset-name" to={`/assets/${a.id}`}>{a.name}</Link><small>{a.manufacturer} · {a.model}</small></td><td>{a.category}</td><td>{a.location||'—'}</td><td><StatusBadge value={a.lifecycle_stage}/></td><td><StatusBadge value={a.condition}/></td><td><StatusBadge value={a.criticality}/></td><td>{a.custodian||'Unassigned'}</td><td><Link aria-label={`View ${a.name}`} className="icon-button" to={`/assets/${a.id}`}><ArrowUpRight size={17}/></Link></td></tr>)}</DataTable>:<EmptyState title="No matching assets"/>}<div className="table-footer">Complete inventory · Search and filters apply across all records</div></section></>;
}
