import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Sparkles, Send, ArrowUpRight } from 'lucide-react';
import { api, useApi } from '../services/api';
import { PageHeading } from '../components/UI';
export default function Assistant(){const [question,setQuestion]=useState(''),[messages,setMessages]=useState([]),[busy,setBusy]=useState(false);const {data:status}=useApi('/assistant/status');
 async function ask(q){if(!q.trim()||busy)return;setQuestion('');setBusy(true);setMessages(m=>[...m,{role:'user',text:q}]);try{const r=await api('/assistant','POST',{question:q});setMessages(m=>[...m,{role:'assistant',...r}]);}catch(e){setMessages(m=>[...m,{role:'assistant',text:e.message,mode:'error'}]);}finally{setBusy(false);}}
 return <><PageHeading eyebrow="ASSET INTELLIGENCE" title="Ask your asset inventory" description="Find equipment, understand maintenance priorities, and review lifecycle alerts."/><section className="card assistant-card"><div className="assistant-header"><span className="assistant-icon"><Sparkles size={23}/></span><div><h2>Asset assistant</h2><p>{status?.configured?'Groq + LangChain · Connected configuration':'Local inventory assistant · No AI key configured'}</p></div><span className="read-only">Read-only</span></div><div className="messages" aria-live="polite">{!messages.length&&<div className="assistant-welcome"><Sparkles size={32}/><h2>Your operations, in plain language.</h2><p>Ask a question to search live records and surface what needs attention.</p><div className="suggestions">{['What maintenance is overdue?','Which warranties expire in the next 90 days?','Show critical assets under maintenance.','Show pumps in poor condition.'].map(q=><button key={q} onClick={()=>ask(q)}>{q}<ArrowUpRight size={15}/></button>)}</div></div>}{messages.map((m,i)=><div className={`message ${m.role}`} key={i}><small>{m.role==='user'?'You':m.mode==='groq'?'Asset assistant · Groq + LangChain':m.mode==='error'?'Connection error':'Asset assistant · Local fallback'}</small><p>{m.text}</p>{m.notice&&<div className="assistant-notice">{m.notice}</div>}{m.assets?.length>0&&<div className="assistant-results">{m.assets.map(a=><Link key={a.id} to={`/assets/${a.id}`}>{a.asset_code} · {a.name}<ArrowUpRight size={14}/></Link>)}</div>}{m.link&&<Link className="card-link" to={m.link}>Open matching records <ArrowUpRight size={14}/></Link>}</div>)}{busy&&<div className="thinking">Checking live inventory…</div>}</div><form className="assistant-input" onSubmit={e=>{e.preventDefault();ask(question);}}><input aria-label="Ask the asset assistant" maxLength={1000} placeholder="Ask about your assets, maintenance, or warranties…" value={question} onChange={e=>setQuestion(e.target.value)}/><button className="button primary" disabled={busy||!question.trim()} aria-label="Send question"><Send size={18}/></button></form><p className="assistant-footnote">Answers use live inventory records. The assistant cannot modify assets. Each question is independent.</p></section></>;
}
