import { Link } from 'react-router-dom';
import { Boxes, IndianRupee, Activity, Wrench, ShieldAlert, ArrowRight, CalendarDays, Download } from 'lucide-react';
import { ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, PieChart, Pie, Cell, CartesianGrid } from 'recharts';
import { useApi, api } from '../services/api';
import { PageHeading, LoadState, StatCard, StatusBadge, AlertCard, Timeline, EmptyState, useApp } from '../components/UI';
import { date, money, label, today, exportCsv } from '../utils/format';
const colors=['#3975ed','#16a58c','#e8ac42','#8e78d7','#eb7180','#84a8f2','#91a3ba','#536881'];
export default function Dashboard(){const {data:d,loading,error,refresh}=useApi('/dashboard');const {notify}=useApp();if(loading||error)return <LoadState loading={loading} error={error} retry={refresh}/>;
 return <><PageHeading eyebrow="OPERATIONS OVERVIEW" title="Every asset. A clearer picture." description="Monitor your infrastructure, stay ahead of maintenance, and keep operations moving."><span className="date-chip"><CalendarDays size={15}/>{date(today())}</span><button className="button" onClick={async()=>{try{exportCsv(await api('/assets'));notify('Inventory exported');}catch(e){notify(e.message);}}}><Download size={15}/>Export inventory</button></PageHeading>
 <div className="overview-strip"><span><span className="live-dot"/> Live inventory</span><span>Pune campus <i>·</i> All locations</span><span>Updated from your asset register</span></div>
 <div className="stats-grid"><StatCard title="Total assets" value={d.summary.totalAssets} note="Across the entire lifecycle" icon={Boxes}/><StatCard title="Asset value" value={money(d.summary.totalAssetValue)} note="Total procurement investment" icon={IndianRupee} tone="violet"/><StatCard title="Operational" value={d.summary.operationalAssets} note={`${d.summary.maintenanceAssets} assets under maintenance`} icon={Activity} tone="green"/><StatCard title="Maintenance due" value={d.summary.maintenanceDue} note="Overdue + next 30 days" icon={Wrench} tone="amber"/><StatCard title="Critical assets" value={d.summary.criticalAssets} note="Critical condition or priority" icon={ShieldAlert} tone="red"/></div>
 <div className="charts-grid"><section className="card"><div className="card-heading"><div><h2>Lifecycle distribution</h2><p>From planning to retirement</p></div><span className="count">{d.summary.totalAssets} assets</span></div><div className="chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={d.stageDistribution.map(x=>({...x,name:label(x.name)}))} margin={{left:-25,right:10,bottom:25}}><CartesianGrid vertical={false} stroke="#edf0f5"/><XAxis dataKey="name" fontSize={10} angle={-25} textAnchor="end" axisLine={false} tickLine={false}/><YAxis allowDecimals={false} fontSize={11} axisLine={false} tickLine={false}/><Tooltip/><Bar isAnimationActive={false} dataKey="value" name="Assets" radius={[5,5,0,0]} maxBarSize={36}>{d.stageDistribution.map((x,i)=><Cell key={x.name} fill={x.name==='OPERATIONAL'?'#3975ed':colors[(i+1)%colors.length]}/>)}</Bar></BarChart></ResponsiveContainer></div></section>
 <section className="card"><div className="card-heading"><div><h2>Asset condition</h2><p>Health of your infrastructure</p></div><span className="subtle">Current</span></div><div className="condition-chart"><div className="donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie isAnimationActive={false} data={d.conditionDistribution} dataKey="value" innerRadius={64} outerRadius={86} paddingAngle={4} stroke="none">{d.conditionDistribution.map((x,i)=><Cell key={x.name} fill={colors[i%colors.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div className="donut-label"><strong>{d.summary.totalAssets}</strong><small>total assets</small></div></div><div className="chart-legend">{d.conditionDistribution.map((x,i)=><div key={x.name}><span style={{background:colors[i]}}/>{label(x.name)}<strong>{x.value}</strong></div>)}</div></div></section></div>
 <div className="panels-grid"><AlertCard title="Maintenance attention" count={d.maintenanceDue.length} link="/maintenance"><p className="panel-description">Prioritize overdue work and upcoming inspections.</p>{d.maintenanceDue.slice(0,5).map(m=><Link className="attention-row" key={m.id} to={`/assets/${m.asset_id}`}><span className={`attention-icon ${m.scheduled_date<today()?'red':'amber'}`}><Wrench size={16}/></span><div><strong>{m.title}</strong><small>{m.asset_code} · {m.asset_name}</small></div><div className="text-right"><span className={`text-tag ${m.scheduled_date<today()?'red-text':''}`}>{m.scheduled_date<today()?'Overdue':'Upcoming'}</span><small>{date(m.scheduled_date)}</small></div></Link>)}{!d.maintenanceDue.length&&<EmptyState title="All caught up"/>}<Link className="card-link" to="/maintenance">View maintenance schedule <ArrowRight size={15}/></Link></AlertCard>
 <AlertCard title="Warranty watch" count={d.warrantyExpiring.length} link="/reports"><p className="panel-description">Coverage ending within the next 90 days.</p>{d.warrantyExpiring.map(a=><Link className="watch-row" key={a.id} to={`/assets/${a.id}`}><div><strong>{a.name}</strong><small>{a.asset_code} · {a.location}</small></div><span className="expiry">{date(a.warranty_expiry)}</span></Link>)}{!d.warrantyExpiring.length&&<EmptyState title="No upcoming expiries"/>}<div className="eol-box"><div><ShieldAlert size={18}/><strong>{d.endOfLifeAssets.length} assets need replacement planning</strong></div><p>Review equipment approaching or past its expected useful life.</p><Link to="/reports">Review lifecycle report <ArrowRight size={14}/></Link></div></AlertCard></div>
 <div className="charts-grid"><section className="card"><div className="card-heading"><div><h2>Assets by category</h2><p>Your infrastructure mix</p></div></div><div className="chart category-chart"><ResponsiveContainer width="100%" height="100%"><BarChart layout="vertical" data={[...d.categoryDistribution].sort((a,b)=>b.value-a.value)} margin={{left:30,right:25}}><XAxis type="number" allowDecimals={false} hide/><YAxis dataKey="name" type="category" width={110} fontSize={11} axisLine={false} tickLine={false}/><Tooltip/><Bar isAnimationActive={false} dataKey="value" name="Assets" fill="#3975ed" radius={[0,4,4,0]} barSize={10}/></BarChart></ResponsiveContainer></div></section><section className="card"><div className="card-heading"><div><h2>Recent asset activity</h2><p>An auditable history of every important change</p></div><span className="live-dot"/></div><Timeline events={d.recentEvents.slice(0,6)}/></section></div></>;
}
