import { useState } from 'react';
import { Link } from 'react-router-dom';
import { Plus, Pencil } from 'lucide-react';
import { useApi } from '../services/api';
import { PageHeading, LoadState, DataTable, StatusBadge, EmptyState } from '../components/UI';
import MaintenanceForm from '../components/MaintenanceForm';
import CompleteMaintenance from '../components/CompleteMaintenance';
import { date, money, label, today } from '../utils/format';
export default function Maintenance(){const {data,loading,error,refresh}=useApi('/maintenance');const [tab,setTab]=useState('All'),[modal,setModal]=useState(null),[complete,setComplete]=useState(null);
 const active=m=>!['COMPLETED','CANCELLED'].includes(m.status);const matches=(m,t)=>t==='All'||(t==='Overdue'&&active(m)&&m.scheduled_date<today())||(t==='Upcoming'&&active(m)&&m.scheduled_date>=today())||(t==='Completed'&&m.status==='COMPLETED');const rows=data?.filter(m=>matches(m,tab));
 return <><PageHeading title="Maintenance workspace" description="Stay ahead of breakdowns. Plan, track, and close every service job."><button className="button primary" onClick={()=>setModal('new')}><Plus size={16}/>Schedule maintenance</button></PageHeading><section className="card"><div className="tabs">{['All','Overdue','Upcoming','Completed'].map(t=><button className={t===tab?'active':''} key={t} onClick={()=>setTab(t)}>{t}<span>{data?.filter(m=>matches(m,t)).length||0}</span></button>)}</div>{loading||error?<LoadState loading={loading} error={error} retry={refresh}/>:rows.length?<DataTable headers={['Asset','Maintenance','Type','Scheduled date','Status','Technician','Cost','Actions']}>{rows.map(m=><tr key={m.id}><td><Link className="code" to={`/assets/${m.asset_id}`}>{m.asset_code}</Link><small>{m.asset_name}</small></td><td><strong>{m.title}</strong></td><td>{label(m.maintenance_type)}</td><td className={active(m)&&m.scheduled_date<today()?'red-text':''}>{date(m.scheduled_date)}{active(m)&&m.scheduled_date<today()&&<small>Overdue</small>}</td><td><StatusBadge value={m.status}/></td><td>{m.technician||'Unassigned'}</td><td>{money(m.cost)}</td><td><div className="actions">{active(m)&&<><button className="button small" onClick={()=>setComplete(m)}>Mark complete</button><button className="icon-button" aria-label={`Edit ${m.title}`} onClick={()=>setModal(m)}><Pencil size={15}/></button></>}</div></td></tr>)}</DataTable>:<EmptyState title={`No ${tab.toLowerCase()} maintenance jobs`}/>}</section>{modal&&<MaintenanceForm record={modal==='new'?null:modal} onClose={()=>setModal(null)} onSaved={refresh}/>} {complete&&<CompleteMaintenance record={complete} onClose={()=>setComplete(null)} onSaved={refresh}/>}</>;
}
