import { NavLink, Link, useLocation, useNavigate } from 'react-router-dom';
import { Boxes, LayoutDashboard, Wrench, MapPin, ChartNoAxesCombined, Sparkles, Search, Plus, PanelLeftClose, Menu } from 'lucide-react';
import { useEffect, useState } from 'react';
import AccountMenu from './AccountMenu';
const nav=[['/','Overview',LayoutDashboard],['/assets','Asset inventory',Boxes],['/maintenance','Maintenance',Wrench],['/locations','Locations',MapPin],['/reports','Reports',ChartNoAxesCombined],['/assistant','Asset assistant',Sparkles]];
export function Sidebar({open,onClose}) {return <><div className={`sidebar-scrim ${open?'visible':''}`} onClick={onClose}/><aside className={`sidebar ${open?'open':''}`}><Link to="/" className="brand"><span className="brand-icon"><Boxes size={24}/></span><div>InfraTrack<small>ASSET LIFECYCLE PLATFORM</small></div></Link><div className="workspace"><span className="workspace-avatar">PC</span><div>Pune campus<small>Infrastructure operations</small></div></div><div className="nav-label">WORKSPACE</div><nav>{nav.map(([path,name,Icon])=><NavLink end={path==='/'} key={path} to={path} onClick={onClose}><Icon size={19}/>{name}{path==='/assistant'&&<span className="new-tag">AI</span>}</NavLink>)}</nav><div className="sidebar-footer"><div className="live-dot"/>Infrastructure Asset Manager<small>Hackathon Prototype · Local workspace</small></div></aside></>;}
export function TopBar({onMenu}) {const location=useLocation(),navigate=useNavigate();const [search,setSearch]=useState('');
 useEffect(()=>{const handler=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();document.getElementById('global-search').focus();}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[]);
 const current=nav.find(([p])=>p!=='/'&&location.pathname.startsWith(p))?.[1]||'Overview';
 return <header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Open menu" onClick={onMenu}><Menu size={20}/></button><PanelLeftClose size={18} className="desktop-icon"/><span>Workspace</span><span>/</span><strong>{current}</strong></div><div className="topbar-right"><form className="global-search" onSubmit={e=>{e.preventDefault();navigate('/assets?search='+encodeURIComponent(search));}}><Search size={16}/><input id="global-search" aria-label="Search inventory" placeholder="Search assets…" value={search} onChange={e=>setSearch(e.target.value)}/><kbd>Ctrl K</kbd></form><Link className="button primary" to="/assets/new"><Plus size={16}/>Add asset</Link><AccountMenu/></div></header>;
}
